### ISSUE TITLE
Empty Asset Browser window

### ISSUE THREAD

**Issue by allansimonsen** [Poly-Haven/polyhavenassets#5] opened 2022-08-28 04:36 UTC
First attempt at using the plug-in. 

Versions used:
Blender 3.1
Plugin 1.0.1

Steps:
- Installed the plugin, and set up the asset path. 
- Opened asset browser, selected Poly Haven, and Fetch Assets
- Plugin started downloading meta-data (verified as showing up in the asset path).
- Initially nothing updated, so I restarted Blender
- The basic catalog (categories, like ALL/HDRIs/Natural Light/Low Contrast) shows, but no assets are visible or useable
- Restarting blender again didn't fix it
- Attempting to disable and re-enable the plugin didn't fix it
- Fetching assets again downloads 0 assets.

Next step will be uninstalling and reinstalling, I guess, but I'm hoping for a solution that doesn't involve pulling another 4GB of data.

**Comment by gregzaal** [comment] 2022-08-29 09:46
Hey,

Normally this behavior is caused by connection issues downloading the files, but v1.0.1 should be reporting these errors to you.

Are any error messages shown in the Info editor after trying to download?

![2022-08-29_11-45-54_blender](https://user-images.githubusercontent.com/5604661/187173824-f523deaa-175c-4bb0-9537-6d812d525b6e.png)

I've also just written a quick troubleshooting guide that may help you with some connection-related issues: https://github.com/Poly-Haven/polyhavenassets/wiki/Download-Troubleshooting

**Comment by allansimonsen** [comment] 2022-08-29 10:07
No errors in Info:
bpy.context.space_data.params.asset_library_ref = 'Poly Haven'
bpy.context.area.ui_type = 'INFO'
Downloading in background...
bpy.ops.pha.pull_from_polyhaven(asset_type="all")
Downloaded 0 assets

I've uninstalled the plugin, currently deleting the assets; will try a clean install and see if it changes things.

**Comment by allansimonsen** [comment] 2022-08-29 10:33
Okay, deleting everything, uninstalling, rebooting Blender, reinstalling, and re-downloading all seems to have fixed things:

There's still some errors in log file, but I think those are more likely the internet being the internet, and not something critical. 

bpy.context.space_data.params.asset_library_ref = 'Poly Haven'
bpy.context.area.ui_type = 'INFO'
Downloading in background...
[SSLError] Error retrieving https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/eilenriede_park_1k.hdr
[SSLError] Error retrieving https://api.polyhaven.com/files/evening_road_01
[SSLError] Error retrieving https://api.polyhaven.com/files/fancy_picture_frame_02
[SSLError] Error retrieving https://api.polyhaven.com/files/freight_station
[SSLError] Error retrieving https://api.polyhaven.com/files/leadenhall_market
[SSLError] Error retrieving https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/large_corridor_1k.hdr
[SSLError] Error retrieving https://api.polyhaven.com/files/modern_buildings_night
[SSLError] Error retrieving https://api.polyhaven.com/files/moulton_station_train_tunnel_west
[SSLError] Error retrieving https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/montorfano_1k.hdr
[ConnectionError] Error retrieving https://api.polyhaven.com/files/rocks_ground_09
[SSLError] Error retrieving https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/wooden_lounge_1k.hdr
[SSLError] Error retrieving https://api.polyhaven.com/files/worn_rock_natural_01
bpy.ops.pha.pull_from_polyhaven(asset_type="all")
Downloaded 994 assets

At least thumbnails now show up, and can be applied to the scene, so the plugin appears to work. Since this is the digital equivalent of giving the old TV a smack to fix it, I'm aware this isn't much use for debugging on your end; sorry :)

**Comment by gregzaal** [comment] 2022-08-29 12:28
Those errors are definitely critical. Without being able to connect to the API and the download server, it can't fetch any assets.

The SSL errors may be resolved by disabling SSL verification in the preferences (shown in the troubleshooting guide I linked earlier). Let me know if that doesn't help.

**Comment by aiNeander** [comment] 2022-08-31 01:39
I am having the same issue. When I uninstalled and reinstalled I got this error:
This script was written Blender version 3.2.0 and might not function (correctly), though it is enabled
Apparently I'm still using Blender 3.0.0
I will update to the latest version of Blender and give it another try, but I'm thinking (hoping) this is the problem.

**Comment by aiNeander** [comment] 2022-08-31 01:49
Update: Updating to the latest version of Blender fixed the problem for me!

**Comment by gregzaal** [comment] 2022-09-22 18:21
Closing due to lack of response, assuming the issue is resolved.

**Closed by gregzaal** 2022-09-22 18:21 UTC
