### ISSUE TITLE
Assets "resets" 

### ISSUE THREAD

**Issue by carlos306** [Poly-Haven/polyhavenassets#123] opened 2024-11-02 20:55 UTC
**Describe the bug**
After installing the poly haven add-on, doing everything what the guide said, and fench the assets, everything seems right, but the problem is when i turn off my pc and open blender again, the assets won't show, even after i revalidate the files, it just show me the message "there is no elements", but in the folder that i put for the file path every assets is downloaded.

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
Too long to be here

```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:

**Expected behavior**
I expect the assets to show everytime i open blender, and that i don't have to unistall and installed again the add-on.

**Screenshots**
![image](https://github.com/user-attachments/assets/b33b477b-ff3e-4ec5-9bdb-60c64b4b79aa)

**Additional context**

**Comment by carlos306** [comment] 2024-11-02 22:31
And when I'm downloading the assets, it stays in 99%. Won't finish the download and stay in 99%



![image](https://github.com/user-attachments/assets/bf6cf928-1083-44d2-9534-85697c424469)

**Comment by gregzaal** [comment] 2024-11-04 10:44
Hi, sorry for the trouble, but I can't reproduce this problem. It's working fine on my end, and I've received no other similar reports.

One things you can check is if there are any filters applied (perhaps accidentally saved as part of your startup file):
![image](https://github.com/user-attachments/assets/104793ee-89f2-4810-bbfc-9505667652b3)

If it's not that, then I will need a more complete bug report (console log pasted or uploaded as a text file, and exact steps for me to reproduce the problem) to be able to help you any further.

Closing this issue for now, but will reopen it if you still have the problem and can provide the additional info.

**Closed by gregzaal** 2024-11-04 10:44 UTC
