### ISSUE TITLE
Download halting issue

### ISSUE THREAD

**Issue by paprikaxu** [Poly-Haven/polyhavenassets#22] opened 2022-10-05 23:49 UTC
<img width="429" alt="Screen Shot" src="https://user-images.githubusercontent.com/4726402/194183625-ac762ead-1c2a-4442-ad7a-c384fbfd25a0.png">

As shown in screenshot above, the fetching progressed till 99% and halted. This is the second attempt, first time it fetched till 94% and halted as well. 

What's the issue here and how do I fix it?

**Comment by gregzaal** [comment] 2022-10-06 04:27
This is likely a connection issue on a particular file, which should resolve itself after some time.

If it persists over more than a day, please open your [system console](https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html) and let me know exactly which file is failing to download so I can investigate further.

**Comment by gregzaal** [comment] 2022-10-20 10:06
Closing this issue as I assume the problem is solved.

**Closed by gregzaal** 2022-10-20 10:06 UTC
