### ISSUE TITLE
python error traceback (most recent call last)

### ISSUE THREAD

**Issue by 39blender** [Poly-Haven/polyhavenassets#95] opened 2023-12-03 17:26 UTC
python error traceback (most recent call last)

**Comment by gregzaal** [comment] 2023-12-04 06:55
Duplicate of #96

**Comment by mcbride19** [comment] 2023-12-10 14:17
python error traceback when fetching the asset library

**Comment by gregzaal** [comment] 2023-12-11 06:59
As explained in the other issue you opened (#96), you have installed the add-on incorrectly.

**Closed by gregzaal** 2023-12-11 06:59 UTC
